import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  root: {
    width: "100%",
    height: "120vh",
    backgroundImage: `url(${"background-img.jpg"})`,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  leftsection: {
    width: "61%",
    backgroundColor: "white",
    height: "100%",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  leftsection_steps: {
    position: "absolute",
    right: "20px",
    top: "20px",
    fontSize: "12px",
    fontWeight: "bold",
  },
  rightsection: {
    width: "33%",
    backgroundColor: "#5a00f8",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    /* marginTop: '20px',
    marginBottom: '20px', */
    fontWeight: "bold",
  },
  subtitle: {
    fontSize: "14px",
  },
  rightsection_title: {
    color: "white",
  },
  rightsection_paragraph: {
    fontFamily: "Arial, Helvetica, sans-serif",
    width: "50%",
    lineHeight: "20pt",
    color: "#fff",
    fontSize: "18px",
    fontWeight: 500,
    marginTop: "60px",
  },
  form: {
    width: "42%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    "& > *": {
      width: "100%",
    },
  },
  leftsection_title: {
    alignSelf: "start",
    width: "40%",
    marginRight: "auto",
    marginLeft: "auto",
  },
  btn: {
    padding: "20px",
    minHeight: 0,
    minWidth: 0,
    backgroundColor: "rgb(40, 110, 250)",
    border: 0,
    borderRadius: 4,
    color: "white",
    fontSize: "16px",
    width: "100%",
  },
  link: {
    color: "#286efa",
    fontWeight: "bold",
  },
  input: {
    border: "1px",
    borderColor: "white",
  },
  errorPassword: {
    color: "#f44336",
    marginLeft: "14px",
    fontSize: "0.75rem",
  },
  testa: {
    position: "fixed",
    width: "100%",
    height: "70px",
    bottom: 0,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  list: {
    listStyle: "none",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginRight: "12px",
    "& > li": {
      opacity: 0.7,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "white",
      border: "1px solid #eee",
      borderRadius: "100%",
      margin: "auto 4px",
      width: "44px",
      height: "44px",
      position: "relative",
      transition: 'all .5s ease-in-out',
      "& span": {
        display: "none",
      },
      "&:hover": {
        opacity: 1,
        cursor: "pointer",
        width: "140px",
        borderRadius: "100px",
        justifyContent: "space-around",
        "&:hover span": {
          display: "inline",
          width: "95px",
          fontSize: "12px",
        },
      },
      "& img": {
        width: "19px",
        height: "18px",
      },
    },
  },
  notification: {
    position: "absolute",
    width: "10px",
    height: "10px",
    borderRadius: "100%",
    backgroundColor: "red",
    top: 0,
    right: 0,
  },
  logo: {
    opacity: 0.7,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "white",
    border: "1px solid #eee",
    borderRadius: "100px",
    marginLeft: "14px",
    padding: "0 14px",
    width: "140px",
    height: "44px",
    fontSize: "12px",
    "& img": {
      width: "19px",
      height: "18px",
    },
    "&:hover": {
      opacity: 1,
      cursor: "pointer",
    },
  },
}));
